name: Deploy preview

on:
  pull_request:
    types: [opened, edited, synchronize]
    branches:
      - master

jobs:
  send_webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deploy
        uses: joelwmale/webhook-action@master
        with:
          url: ${{ secrets.DEPLOY_PREVIEW_WEBHOOK_URL }}
          body: '{"data": "${{ github.head_ref }}"}'
