name: 'Dependency review'

on:
  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened]
    paths:
      - '.github/workflows/**.yml'

permissions:
  contents: read
  pull-requests: write

jobs:
  vulnerability-check:
    uses: Enigmatic-Smile/gh-automation/.github/workflows/dependency-review.yml@main
    permissions:
      contents: read
      pull-requests: write
